

services:
  postgres-dem:
    image: postgres:16
    container_name: postgres-dem
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dem_data:/var/lib/postgresql/data

volumes:
  postgres_dem_data:
